### ISSUE TITLE
pip install vmprof==0.4.10 fails on osx

### ISSUE THREAD

**Issue by rappdw** [vmprof/vmprof-python#160]
The following error occurs pip installing 0.4.10. pip install vmprof==0.4.9 succeeds
    
/usr/bin/clang -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.6/src/_vmprof.o build/temp.macosx-10.6-intel-3.6/src/machine.o build/temp.macosx-10.6-intel-3.6/src/compat.o build/temp.macosx-10.6-intel-3.6/src/vmp_stack.o build/temp.macosx-10.6-intel-3.6/src/vmprof_common.o build/temp.macosx-10.6-intel-3.6/src/vmprof_memory.o build/temp.macosx-10.6-intel-3.6/src/symboltable.o build/temp.macosx-10.6-intel-3.6/src/vmprof_unix.o build/temp.macosx-10.6-intel-3.6/src/vmprof_mt.o -o build/lib.macosx-10.6-intel-3.6/_vmprof.cpython-36m-darwin.so
    duplicate symbol __PyThreadState_Current in:
        build/temp.macosx-10.6-intel-3.6/src/_vmprof.o
        build/temp.macosx-10.6-intel-3.6/src/vmprof_common.o
    duplicate symbol __PyThreadState_Current in:
        build/temp.macosx-10.6-intel-3.6/src/_vmprof.o
        build/temp.macosx-10.6-intel-3.6/src/vmprof_unix.o
    ld: 2 duplicate symbols for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/bin/clang' failed with exit status 1

**Comment by antocuni** [comment]
I assume you are talking about CPython, aren't you? Which version of CPython is it?
I just realized that the CPython 3.4+MacOS X build [never completed](https://travis-ci.org/vmprof/vmprof-python/builds/295107396), and thus there is no binary wheel for it.

What happens if you run the following? (to force pip to compile vmprof 0.4.9 from source)
```
pip install vmprof==0.4.9 -U --force-reinstall --no-cache-dir --no-binary :all:
```

**Comment by rappdw** [comment]
A bit more detail. From a fresh virtualenv, with python 3.6.3 (pip list shows only pip and setuptools):

pip install vmprof==0.4.9 succeeds,
pip install vmprof==0.4.9 -U --force-reinstall --no-cache-dir --no-binary :all: succeeds,

pip install vmprof==0.4.10 results in the following error log
[error.txt](https://github.com/vmprof/vmprof-python/files/1441242/error.txt)

**Comment by planrich** [comment]
I have restarted the build and it now uploaded the binary wheel for mac os x. (See here https://pypi.python.org/pypi/vmprof/0.4.10 ). I assume this should fix the problem?

**Comment by jonashaag** [comment]
It misses a Python 3.6 wheel.

**Comment by rappdw** [comment]
@planrich Still not fixed (although I'm not sure the build has run since https://github.com/vmprof/vmprof-python/issues/160

**Comment by planrich** [comment]
Nope, I'm planning a pre release soon. That should build cpython 3.6 wheel for mac.

**Comment by planrich** [comment]
Ok, this should be fixed as of 0.4.11.dev1 has mac os x wheels of cpython 3.6. (See https://pypi.python.org/pypi/vmprof/0.4.11.dev1).

0.4.11.dev2 should be up soon as well.

**Comment by jonashaag** [comment]
@planrich Just a quick heads up that `pip install vmprof` is still broken on OSX (but `pip install --pre vmprof` works)
